### ISSUE TITLE
its no longuer working 

### ISSUE THREAD

**Issue by Scorpiopt** [Rall3n/galaxy-integration-amazon#37] opened 2024-08-16 18:20 UTC
keeps claims technical problems 24/7

workaround  
Credit to Nephilim983 on origin forums 

Open Users/"User name"/AppData/Local/GOG.com/Galaxy/plugins/installed/origin_xxxxx/plugin.py in Notepad. Replace lines 38-47 with following:

AUTH_PARAMS = {
"window_title": "Login to EA Play",
"window_width": 495 if is_windows() else 480,
"window_height": 746 if is_windows() else 708,
"start_uri": "https://accounts.ea.com/connect/auth"
"?response_type=code&client_id=EADOTCOM-WEB-SERVER&display=junoWeb/login"
"&locale=en_US&release_type=prod"
"&redirect_uri=https://www.ea.com/ea-play",
"end_uri_regex": "https://www.ea.com/ea-play"
}

This will allow you to log in with a small caveat, Login window won't close. To complete login, just click on EA Play logo at top of the window page. The window will close, and the connection will be established.

**Comment by Germaenace** [comment] 2024-08-17 11:02
Thanks for the workaround. but what you describe is for EA, not amazon prime gaming. or am I missing sth?

unfortunately the amazon plugin isnt working for me as well.
in the plugin settings in gog it just says the plugin crashed.

**Comment by Scorpiopt** [comment] 2024-08-17 11:04
> Thanks for the workaround. but what you describe is for EA, not amazon prime gaming. or am I missing sth?
> 
> unfortunately the amazon plugin isnt working for me as well. in the plugin settings in gog it just says the plugin crashed.

Ah shit had both tabs open and posted on the wrong one

**Comment by Rall3n** [comment] 2024-08-27 22:45
@Germaenace Unfortunately, i can't find an issue with the plugin in its current state.

Could u provide the latest Amazon plugin log file located in `%PROGRAMDATA%\GOG.com\Galaxy\logs\`?

**Comment by Rall3n** [comment] 2024-10-18 11:11
Closing as can't reproduce and no log files with error provided.

**Closed as not planned by Rall3n** 2024-10-18 11:11 UTC

**Comment by paulochf** [comment] 2024-12-02 03:09
I can provide the logs. I clicked the Allow button a lot.

```
2024-12-02 00:04:07,802 - root - DEBUG - Using proactor: IocpProactor
2024-12-02 00:04:07,803 - galaxy.api.plugin - INFO - Using local address: 127.0.0.1:52904
2024-12-02 00:04:07,804 - galaxy.api.plugin - INFO - Creating plugin for platform amazon, version 0.5.2
2024-12-02 00:04:07,812 - galaxy.api.jsonrpc - INFO - Handling request: id=0, method=get_capabilities, params={}
2024-12-02 00:04:07,812 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "0", "result": {"platform_name": "amazon", "features": ["ShutdownPlatformClient", "LaunchGame", "ImportOSCompatibility", "LaunchPlatformClient", "ImportOwnedGames", "UninstallGame", "ImportInstalledGames"], "token": "377adb6d-9b6c-4a1e-aa87-e87804dcdd1d"}}
2024-12-02 00:04:07,923 - galaxy.api.jsonrpc - INFO - Handling request: id=1, method=initialize_cache, params={'data': '****'}
2024-12-02 00:04:07,923 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "1", "result": null}
2024-12-02 00:04:07,928 - galaxy.api.jsonrpc - INFO - Handling request: id=2, method=ping, params={}
2024-12-02 00:04:07,929 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "2", "result": null}
2024-12-02 00:04:09,457 - galaxy.api.jsonrpc - INFO - Handling request: id=3, method=import_local_games, params={}
2024-12-02 00:04:09,572 - galaxy.api.jsonrpc - INFO - Handling request: id=4, method=init_authentication, params={}
2024-12-02 00:04:09,573 - amazonPlugin - INFO - Plugin authenticate
2024-12-02 00:04:09,573 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "4", "result": {"next_step": "web_session", "auth_params": {"window_title": "GOG Galaxy 2.0 - Amazon Games Integration", "window_width": 560, "window_height": 710, "start_uri": "file:///C:/Users/Paulo/AppData/Local/GOG.com/Galaxy/plugins/installed/amazon/splash/index.html?view=splash", "end_uri_regex": ".*splash_continue.*"}}}
2024-12-02 00:04:10,766 - galaxy.api.jsonrpc - INFO - Handling request: id=5, method=pass_login_credentials, params={'cookies': '****', 'credentials': '****', 'step': ''}
2024-12-02 00:04:10,767 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "5", "result": {"next_step": "web_session", "auth_params": {"window_title": "GOG Galaxy 2.0 - Amazon Games Integration", "window_width": 560, "window_height": 710, "start_uri": "file:///C:/Users/Paulo/AppData/Local/GOG.com/Galaxy/plugins/installed/amazon/splash/index.html?view=missing-app", "end_uri_regex": ".*missing_app_retry.*"}}}
2024-12-02 00:04:12,938 - galaxy.api.jsonrpc - INFO - Handling request: id=6, method=ping, params={}
2024-12-02 00:04:12,938 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "6", "result": null}
2024-12-02 00:04:13,609 - galaxy.api.jsonrpc - INFO - Handling request: id=7, method=pass_login_credentials, params={'cookies': '****', 'credentials': '****', 'step': ''}
2024-12-02 00:04:13,610 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "7", "result": {"next_step": "web_session", "auth_params": {"window_title": "GOG Galaxy 2.0 - Amazon Games Integration", "window_width": 560, "window_height": 710, "start_uri": "file:///C:/Users/Paulo/AppData/Local/GOG.com/Galaxy/plugins/installed/amazon/splash/index.html?view=missing-app", "end_uri_regex": ".*missing_app_retry.*"}}}
2024-12-02 00:04:14,703 - galaxy.api.jsonrpc - INFO - Handling request: id=8, method=pass_login_credentials, params={'cookies': '****', 'credentials': '****', 'step': ''}
2024-12-02 00:04:14,704 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "8", "result": {"next_step": "web_session", "auth_params": {"window_title": "GOG Galaxy 2.0 - Amazon Games Integration", "window_width": 560, "window_height": 710, "start_uri": "file:///C:/Users/Paulo/AppData/Local/GOG.com/Galaxy/plugins/installed/amazon/splash/index.html?view=missing-app", "end_uri_regex": ".*missing_app_retry.*"}}}
2024-12-02 00:04:15,580 - galaxy.api.jsonrpc - INFO - Handling request: id=9, method=pass_login_credentials, params={'cookies': '****', 'credentials': '****', 'step': ''}
2024-12-02 00:04:15,581 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "9", "result": {"next_step": "web_session", "auth_params": {"window_title": "GOG Galaxy 2.0 - Amazon Games Integration", "window_width": 560, "window_height": 710, "start_uri": "file:///C:/Users/Paulo/AppData/Local/GOG.com/Galaxy/plugins/installed/amazon/splash/index.html?view=missing-app", "end_uri_regex": ".*missing_app_retry.*"}}}
2024-12-02 00:04:16,600 - galaxy.api.jsonrpc - INFO - Handling request: id=10, method=shutdown, params={}
2024-12-02 00:04:16,600 - galaxy.api.plugin - INFO - Shutting down
2024-12-02 00:04:16,600 - galaxy.api.plugin - INFO - Closing plugin
2024-12-02 00:04:16,600 - galaxy.api.jsonrpc - INFO - Closing JSON-RPC server - not more messages will be read
2024-12-02 00:04:16,601 - galaxy.api.jsonrpc - ERROR - Sending data: {"jsonrpc": "2.0", "id": "3", "error": {"code": -32001, "message": "Method aborted", "data": {"internal_type": "Aborted"}}}
2024-12-02 00:04:17,006 - galaxy.api.jsonrpc - INFO - Sending data: {"jsonrpc": "2.0", "id": "10", "result": null}
2024-12-02 00:04:17,006 - galaxy.api.plugin - INFO - Plugin closed

```

**Comment by paulochf** [comment] 2024-12-02 03:19
Oh, I got it. It requires the Amazon game client installed previous to the integration connection. I've just read it from the connection popup.

I think having this requirement explicitly described in the README in all caps would draw one's attention and solve it.
