### ISSUE TITLE
Narcos is linked to wrong gamepage

### ISSUE THREAD

**Issue by cmdr-keen** [Rall3n/galaxy-integration-amazon#14] opened 2021-03-09 15:19 UTC
Narcos (Narcos: Rise of the Cartels) is linked to an old game (Doom clone, 1999?) with the same title that you can barely find any info on.

**Comment by Rall3n** [comment] 2021-03-20 11:54
Thanks for bringing that issue to my attention.

I'm currently trying to create a fix for that, but I can't test it until I somehow reset my Amazon part of the GOG Galaxy 2.0 database.

**Comment by Rall3n** [comment] 2021-04-17 14:07
To provide some clarification:

The Amazon Games app lists the game `Narcos: Rise of the Cartels` with simply `Narcos` as its title. This is the cause of why the game information for `Narcos 1999` is used inside of GOG Galaxy.

I could (and will) change the title inside the plugin to the correct one, but this  fix would not affect current users as GOG Galaxy refuses to take the updated title from the plugin. This would (in theory) only provide a fix for users installing the plugin from scratch (no re-installation as games in the library are saved in the cloud).

**Comment by Rall3n** [comment] 2021-04-19 10:08
Issue has been fixed by GOG (see gogcom/galaxy-integrations-python-api#177). After accessing the game page of the current game, the information reset to the actual game.

But I will still release a new version with changed game titles. I will keep this issue open until then.

**Comment by Rall3n** [comment] 2021-04-23 14:50
After some consideration, I am now against creating a fix that has no effect.

As mentioned in the GOG issue, the plugin developers currently have no control over the title after it has been registered for the first time. So a fix on the plugins side would not help at all, as any change would be ignored by Galaxy. And you only find out about this problem after the game has been registered in Galaxy.

I'm sorry if I couldn't provide a solution to your problem on the plugins side, but my hands are tied in this regard.

**Closed as completed by Rall3n** 2021-04-23 14:50 UTC
